# Powerline theme variables
POWERLINE_RIGHT_A="mixed"
POWERLINE_DATE_FORMAT="%D{%d/%m}"
POWERLINE_MULTILINE="true"

# Powerlevel10k variables
POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND='white'
POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND='grey30'
POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND='red'
POWERLEVEL9K_CONTEXT_ROOT_BACKGROUND='black'
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir dir_writable vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs history time)
POWERLEVEL9K_TIME_FORMAT="%D{%H:%M}"
POWERLEVEL9K_TIME_ICON=""
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="🀄"
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="↪ "
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true