
add_newline = true

[aws]
disabled = true

[conda]
disabled = true

[dotnet]
disabled = true

[nodejs]
disabled = true

[battery]
disabled = true

[directory]
truncation_length = 5

[character]
success_symbol = "﬌"
error_symbol = "✗"
use_symbol_for_status = true

[username]
style_root = "bold red"
style_user = "bold yellow"
show_always = true
disabled = false

[time]
format = "%H:%M "
style = "bold yellow"
disabled = false

[hostname]
ssh_only = false
style = "bold green"
disabled = false
