#!/bin/sh

bspc rule -r "*"

bspc monitor PAD -r
bspc monitor RACK -r

bspc wm -a PAD 1920x1080+3840+0
bspc wm -a RACK 3840x1080+0+0

bspc monitor DVI-D-1 -d H I L
bspc monitor HDMI-1 -d V W X Y
bspc monitor PAD -d Xpad
bspc monitor RACK -d Xrack

bspc wm --reorder-monitors DVI-D-1 HDMI-1 PAD RACK

# master/stack layout
bsp-layout set tall H
bsp-layout set tall I
bsp-layout set tall L 
bsp-layout set tall V
bsp-layout set tall W
bsp-layout set tall X
bsp-layout set tall Y

# polybspwm &
autostart &
pidof bspswallow || bspswallow &

bspc config border_width         			2
bspc config window_gap          			10

bspc config presel_feedback_color			"#95D8E1"

bspc config split_ratio          			0.50
bspc config borderless_monocle   			true
bspc config gapless_monocle      			true
bspc config top_monocle_padding				-25
bspc config focus_follows_pointer 			true
bspc config pointer_follows_monitor			true
bspc config ignore_ewmh_focus 				true
bspc config automatic_scheme				spiral
bspc config top_padding 					25

bspc config pointer_modifier				mod4
bspc config pointer_action1					move
bspc config pointer_action2					resize_corner

bspc rule -a GLFW-Application				desktop='Xrack' follow=on

bspc rule -a Carla2-Multi-Client -o			desktop='Xpad' state=floating center=on rectangle=1200x700+0+0
bspc rule -a Thunderbird -o					desktop='Xpad' state=floating center=on rectangle=1200x900+0+0

bspc rule -a Carla2-Multi-Client			state=floating center=on follow=on
bspc rule -a Thunderbird					state=floating center=on follow=on
bspc rule -a feh							state=floating center=on
bspc rule -a Yad							state=floating
bspc rule -a floaterm						state=floating center=on rectangle=1100x730+0+0
bspc rule -a Cadence						state=floating center=on rectangle=800x730+0+0
bspc rule -a MEGAsync						state=floating center=on border=off rectangle=300x500+0+0
bspc rule -a SimpleScreenRecorder			state=floating center=on
bspc rule -a Lxappearance					state=floating center=on
bspc rule -a Zathura 						state=tiled
bspc rule -a Gnome-disks 					state=floating
# bspc rule -a Sol							state=floating center=on
bspc rule -a Maitreya8.bin 					state=floating
bspc rule -a Xmj		 					state=floating center=on
bspc rule -a GParted		 				state=floating center=on
