[icons]
# font awesome
firefox = ""
Vivaldi-stable = ""
Thunderbird = ""
Sol = ""
Mousepad = ""
"VirtualBox Manager" = ""
Clementine = ""
SimpleScreenRecorder = ""
Carla2-Multi-Client = ""
Pcmanfm = ""
code-oss = ""
Geany = ""
Mixxx = ""
kitty = ""
GParted = ""
Openastro = ""
Gnome-disks = ""
Gucharmap = ""
Shotwell = ""
Gpick = ""
multibootusb = ""
Pamac-manager = ""
Audacity = ""
Cadence = ""
"Gimp-2.10" = ""
"GLFW-Application" = ""
Typora = ""
GitKraken = ""
"Maitreya8.bin" = ""
"Brave-browser" =""

[aliases]
firefox = "Firefox"
Vivaldi-stable = "Vivaldi"
Gnubg = "Backgammon"
"VirtualBox Manager" = " VBox"
SimpleScreenRecorder = "Screen Rec"
Carla2-Multi-Client ="Carla"
code-oss = "Code"
kitty = "Kitty"
Polkit-gnome-authentication-agent-1 = "GKSU"
Gnome-disks = "Disks"
Gucharmap = "Characters"
multibootusb = "MultibootUSB"
Pamac-manager = "Pamac"
"Gimp-2.10" = "Gimp"
"GLFW-Application" = "VCV Rack"
"Maitreya8.bin" = "Maitreya"
"Brave-browser" = "Brave"
